// Generated by CoffeeScript 1.8.0
(function() {
  var Clipboard, format;

  Clipboard = (function() {
    function Clipboard() {}

    Clipboard.prototype.get = function() {
      var ta;
      ta = document.createElement('textarea');
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('paste');
      document.body.removeChild(ta);
      return ta.value;
    };

    Clipboard.prototype.set = function(text) {
      var ta;
      ta = document.createElement('textarea');
      document.body.appendChild(ta);
      ta.value = text;
      ta.select();
      document.execCommand('copy');
      return document.body.removeChild(ta);
    };

    return Clipboard;

  })();

  format = function(text) {
    return text.replace(/\n\-{5} \w+ \d+\w+, \d+ \-{5}\n/mg, '').replace(/^(\w+)\s+(\[\d{2}:\d{2}\])\s*$/mg, '**$1** *$2*');
  };

  document.addEventListener('copy', function(e) {
    return setTimeout(function() {
      var c, text;
      c = new Clipboard;
      text = c.get();
      return console.log(format(text));
    }, 0);
  });

}).call(this);
